global:
  scrape_interval:     1s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'demo-monitor'

rule_files:
  - '/etc/prometheus/prometheus.rules.yml'

# A scrape configuration containing two endpoints to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'metrics'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # By default, the metrics path is `/metrics`
    metrics_path: /

    static_configs:
      - targets: ['hostname:8000']
